easy_admin:
    site_name: 'Fortuna'
    design:
        color_scheme: 'dark'
        menu:
            - label: 'Opciones SA'
              icon: 'cog'
              children:
                    - { label: 'Usuarios', entity: 'User', icon: 'user' }
                    - { label: 'Configuración', entity: 'Config', icon: 'users' }
#            - label: 'menu.product'
#              icon: 'shopping-basket'
#              children:
#                  - { entity: 'Product', icon: 'th-list', label: 'menu.product.list', params: { sortField: 'createdAt' }, default: true }
#                  - { entity: 'Category', icon: 'tags', label: 'menu.category' }
#                  - { entity: 'Product', icon: 'plus-circle', label: 'menu.product.add', params: { action: 'new' } }
            #- { label: 'Usuarios', entity: 'User', icon: 'users' }
            #- { label: 'Config', entity: 'Config', icon: 'cog' }
#            - { label: 'menu.purchase', entity: 'Purchase', icon: 'credit-card', params: { sortField: 'deliveryDate' } }
#            - { label: 'menu.about' }
#            - { label: 'menu.about.home', url: 'https://github.com/javiereguiluz/EasyAdminBundle', icon: 'home', target: '_blank' }
            - { label: 'Configuración', route: 'config', icon: 'cog' }
#            - { label: 'menu.about.issues', url: 'https://github.com/javiereguiluz/EasyAdminBundle/issues', icon: 'github', target: '_blank' }
