<?php

namespace AppBundle\Repository;

/**
 * EventosInstitucionalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventosInstitucionalesRepository extends \Doctrine\ORM\EntityRepository
{
}
