imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: admin/ }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    app.path.user_images: /uploads/images/users
    #vichuploader

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    form_themes:
        - 'AppBundle:Form:fields.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    disable_delivery:  false

#web_profiler:
#    toolbar: true
#    intercept_redirects: false

#vich uploader configuration
vich_uploader:
    db_driver: orm
    storage: file_system
    twig: true

    mappings:
        recepcion_pago_image:
            uri_prefix:         /fortuna/web/uploads/sorteo
            upload_destination: %kernel.root_dir%/../web/uploads/sorteo
            namer:              vich_uploader.namer_origname

            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

easy_admin:
    entities:
#        - AppBundle\Entity\User
        User:
            class: AppBundle\Entity\User
            controller: AppBundle\Controller\AdminController
            list:
                fields:
                    - id
                    - username
                    - email
                    - nombre
                    - apellido
                    - enabled
                actions:
                    - { name: 'show', icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }
            new:
                title: 'Añadir un nuevo usuario'
                fields:
                    - username
                    - email
                    - roles
                    - enabled
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - nombre
                    - apellido
                    #- { property: 'plainPassword', type: 'text', type_options: { required: true } }
                    - { property: 'plainPassword', type: 'repeated', type_options: { type: 'password', invalid_message: 'Las dos contraseñas deben coincidir', first_options: { label: 'Contraseña' }, second_options: { label: 'Confirmar Contraseña' }, required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_MANAGER': 'ROLE_MANAGER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Registration'] }
            edit:
                title: 'Edición de información de usuarios'
                fields:
                    - username
                    - email
                    - roles
                    - enabled
                    - nombre
                    - apellido
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    #- { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'plainPassword', type: 'repeated', type_options: { type: 'password', invalid_message: 'Las dos contraseñas deben coincidir', first_options: { label: 'Contraseña' }, second_options: { label: 'Confirmar Contraseña' }, required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_MANAGER': 'ROLE_MANAGER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Profile'] }
        Config:
            class: AppBundle\Entity\Config

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: '%mailer_user%'
        sender_name: '%app_name%'
    registration:
        form:
            type: AppBundle\Form\RegistrationType
        confirmation:
            enabled: true
    profile:
        form:
            type: AppBundle\Form\ProfileType

#vichuploder configuration
vich_uploader:
    db_driver: orm
    mappings:
        user_images:
            uri_prefix:         '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/users'
