<?php

namespace AppBundle\Entity;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RecargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecargaRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($searchParam) {
        extract($searchParam);
       $qb = $this->createQueryBuilder('r')
            ;

        if(!empty($keyword))
            $qb->andWhere('r.codigo like :keyword or r.recarga like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');

        if(!empty($sortBy)){
            $sortBy = in_array($sortBy, array('codigo', 'recarga')) ? $sortBy : 'id';
            $sortDir = ($sortDir == 'DESC') ? 'DESC' : 'ASC';
            $qb->orderBy('r.' . $sortBy, $sortDir);
        }
        if(!empty($perPage)) $qb->setFirstResult(($page - 1) * $perPage)->setMaxResults($perPage);

       return new Paginator($qb->getQuery());
    }

    public function counter() {
        $qb = $this->createQueryBuilder('r')->select('COUNT(r)');
        return $qb->getQuery()->getSingleScalarResult();
        //$sql = 'SELECT count(u) FROM AppBundle\Entity\Sorteo u';
        //$query = $this->_em->createQuery($sql);
        //return $query->getOneOrNullResult();
    }
}
